### PR TITLE
httpd/server: Also capture loginuid of the remote process

### PR DESCRIPTION
**Pull request by shaded-enmity**
To clarify the implementation:
 `e.errno == 2` is `ENOENT` (file not found)

### CODE REVIEW

**Comment by shaded-enmity** [comment]
Updated & Rebased

**Comment by shaded-enmity** [comment]
WRT reading /proc, sadly thats the only way possible. Function `audit_getloginuid(void)` from `pam_loginuid` returns per-process value.

**Comment by shaded-enmity** [comment]
Rebased once more (turn -1 into None)

**Comment by shaded-enmity** [comment]
2 --> `errno.ENOENT`

Deterministic `loginuid` or `None`

**Comment by shaded-enmity** [comment]
Moved `loginuid` to a member variable of the handler

**Comment by simo5** [comment]
Thank you,
pushed to master

**Pull request closed without merging**
